on: [pull_request]

name: Package vsix
jobs:
  artifact:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: install cdn-uploader
        run: npm i -g @dcl/cdn-uploader@next

      - name: npm install
        run: npm install

      - name: get latest release
        uses: pozetroninc/github-action-get-latest-release@master@v0.7.0
        id: editor_release
        with:
          repository: 'decentraland/editor-sdk7'

      - name: get commit
        run: echo "COMMIT_HASH=$(git rev-parse --short "$GITHUB_SHA")"  >> $GITHUB_ENV

      - name: build artifact (vsix)
        run: mkdir artifacts && npx vsce package ${{steps.editor_release.outputs.release}}-${{ env.COMMIT_HASH }} -o "$_/editor-sdk7.vsix"

      - name: upload artifact to S3
        run: npx @dcl/cdn-uploader@next --bucket ${{ secrets.SDK_TEAM_S3_BUCKET }} --local-folder $(pwd)/artifacts --bucket-folder 'editor-sdk7/branch/${{ github.head_ref || github.ref }}/artifacts'
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.SDK_TEAM_AWS_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.SDK_TEAM_AWS_SECRET }}

  notify_deployment:
    needs: [artifact]
    runs-on: ubuntu-latest
    name: Deployment Notification
    steps:
      - name: Find Comment
        uses: peter-evans/find-comment@v1
        id: fc
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: 'github-actions[bot]'
          body-includes: Test this pull request
      - name: Create or update comment
        uses: peter-evans/create-or-update-comment@v1
        with:
          comment-id: ${{ steps.fc.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            # Test this pull request
            - The `editor-sdk7` extension can be tested in VSCode by downloading [this](${{ secrets.SDK_TEAM_S3_BASE_URL }}/editor-sdk7/branch/${{ github.head_ref || github.ref }}/artifacts/editor-sdk7.vsix) `.vsix` file and running:

               ```bash
               code --force --install-extension editor-sdk7.vsix
               ```
          edit-mode: replace
